name: Build and deploy Python app to Azure Web App - HealthA

on:
  push:
    branches:
      - Free-plan
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Copy services to the app directory
        run: |
                cp -r backend/* .
                cp -r bmi_service/* .
                cp -r bmr_service/* .
                cp -r frontend/* .
                

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A676C65A439429E994F70636DA594C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7EA2B5F0C2EA4EA0946ABB8BC4254773 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBE59B972E84A5EAFEB4D4ED38DFBC7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'HealthA'
          slot-name: 'Production'
          startup-command: 'gunicorn backend.app:app'
